// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAP69vMSwo22fkO0D1J1w1LqeTeR9iIfM',
    appId: '1:1019230815479:web:09c26fecf120d69230fff2',
    messagingSenderId: '1019230815479',
    projectId: 'callmessage-d9f69',
    authDomain: 'callmessage-d9f69.firebaseapp.com',
    storageBucket: 'callmessage-d9f69.firebasestorage.app',
    measurementId: 'G-HX4HZX9DH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNfm4Cv8ipMkdqXhV0pfA_Mj-hOzoTksQ',
    appId: '1:1019230815479:android:a602b14c515031ab30fff2',
    messagingSenderId: '1019230815479',
    projectId: 'callmessage-d9f69',
    storageBucket: 'callmessage-d9f69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEYjthSCVYa3-coxniTqwcD5WjQ-1uox8',
    appId: '1:1019230815479:ios:ae96c8b0b3c6a0c430fff2',
    messagingSenderId: '1019230815479',
    projectId: 'callmessage-d9f69',
    storageBucket: 'callmessage-d9f69.firebasestorage.app',
    iosBundleId: 'com.example.testingPurpose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEYjthSCVYa3-coxniTqwcD5WjQ-1uox8',
    appId: '1:1019230815479:ios:ae96c8b0b3c6a0c430fff2',
    messagingSenderId: '1019230815479',
    projectId: 'callmessage-d9f69',
    storageBucket: 'callmessage-d9f69.firebasestorage.app',
    iosBundleId: 'com.example.testingPurpose',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAP69vMSwo22fkO0D1J1w1LqeTeR9iIfM',
    appId: '1:1019230815479:web:b2c4e728076a7cf130fff2',
    messagingSenderId: '1019230815479',
    projectId: 'callmessage-d9f69',
    authDomain: 'callmessage-d9f69.firebaseapp.com',
    storageBucket: 'callmessage-d9f69.firebasestorage.app',
    measurementId: 'G-2P6MQNB0L2',
  );
}
